# Generated by Django 2.2.24 on 2021-08-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210729_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key_expires',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
